### ISSUE TITLE
Does the version of spec2017 affect patching?

### ISSUE THREAD

**Issue by CrowGao** [prietop/BenchCast#1]
error:
[root@CPU2017]# git apply SPEC17.patch  --whitespace=fix
SPEC17.patch:648: trailing whitespace.
      
SPEC17.patch:769: trailing whitespace.
       
SPEC17.patch:778: trailing whitespace.
       
SPEC17.patch:779: trailing whitespace.
       
SPEC17.patch:780: trailing whitespace.
c        Adjustment of artificial viscosity 
error: patch failed: bin/common/setup_common.pl:217
error: bin/common/setup_common.pl: patch does not apply
error: cpu2017-1_0_2.iso: No such file or directory

How to fix it?

**Comment by prietop** [comment]
Thanks for pointing this out. I've removed the reference to cpu2017-1_0_2.iso, which was an error and shouldn't be in the patch. The SPEC17.patch file has been updated in a commit, so you can update your repository. 
I suspect the setup_common.pl problem may be an issue with the spec2017 version, but I will try to check it if I can. The only thing that portion of the patch does is comment out the line that changes the value of check_integrity when the code has been modified. We are modifying the code of the SPEC 2017 apps to work with our tool and this could cause the SPEC to fail due to a code integrity failure. You can remove these lines from the patch file (now lines 15496 to 15506) and try to modify the line that changes the value of check_integrity from your setup_common.pl file yourself.
(comment the line that says "$::check_integrity=1;")
If you can keep us updated on the progress of this issue, it will be greatly appreciated.

**Comment by CrowGao** [comment]
What is the version of sepc2017 you are using？And  can't delete lines 15496 to 15506 of SEPC17.path, but lines 15494 to 15506.
![243616b454545a0cfcf1039044e082c9](https://github.com/prietop/BenchCast/assets/97955088/4f17f273-8ce4-49ee-b531-6f8d3fe308d9)

**Comment by prietop** [comment]
That's right, lines 15494 through 15506. The paper and patch were created using version 1.0.2 of SPEC 2017, as the SPEC part of the tool is from a simpler earlier version. I have checked how integrity is handled in the latest versions, and it appears that there is a change in the previous "if" that causes the problem with the patch (line to comment is 221 in setup_common.pl in SPEC 2017 1.1.9 version). But looking at the previous "if" and considering that we set the SPEC_NOCHECK variable, it may not be needed anymore. This needs to be tested.

**Comment by CrowGao** [comment]
**I modify the line that changes the value of check_integrity from my setup_common.pl file myself，but it don't work.**
[CPU2017]# git apply --ignore-whitespace SPEC17.patch
SPEC17.patch:648: trailing whitespace.
      
SPEC17.patch:769: trailing whitespace.
       
SPEC17.patch:778: trailing whitespace.
       
SPEC17.patch:779: trailing whitespace.
       
SPEC17.patch:788: trailing whitespace.
     
fatal: patch with only garbage at line 15449

**And bin/common/setup_common.p is modified**
215 sub check_important_files {
216     my ($re) = @_;
217 
218     # CVT2DEV: $::check_integrity = 0; return;
219     return if (::is_devel($::suite_version) and !$ENV{'SPEC_CHECK'})
220         or (::is_release($::suite_version) and $ENV{'SPEC_NOCHECK'});
221     # $::check_integrity = 1;
222     # Who I Am is actually the last three components of the path, which should be
223     # 'bin' / (harness|formatter) / <me>

**Comment by CrowGao** [comment]
In Our SPEC2017_0.8 version, there is nothing uncommented on lines 85 and 283 of /benchspec/Makefile.defaults.
![1e7925442698d0be0dd1953da86461e6](https://github.com/prietop/BenchCast/assets/97955088/590ed38b-542e-45d6-90a6-e601008d4cdf)
![6e7bf10ea247a5b27cf263690ef1dcb2](https://github.com/prietop/BenchCast/assets/97955088/6977e7fe-9c0a-41da-a8f3-3b9cf7ea8f65)

**Comment by prietop** [comment]
The portion of the patch corresponding to the setup_common.pl should be (for spec 2017 version 1.1.9) something like:

```
@@ -218,7 +218,7 @@
     # CVT2DEV: $::check_integrity = 0; return;
     return if (::is_devel($::suite_version) and !$ENV{'SPEC_CHECK'})
         or (::is_release($::suite_version) and $ENV{'SPEC_NOCHECK'});
-    $::check_integrity = 1;
+    #$::check_integrity = 1;
     \# Who I Am is actually the last three components of the path, which should be
     \# 'bin'  / (harness|formatter) / <me>
     my $whoami;

```
However, if you have problems with these lines in the patch file, you should remove them and apply the changes yourself.

The lines in Makefile.defaults should not be present in the original files, as they were added by us. After applying the patch, the commented lines should be there, and you can uncomment any of them to run with gem5 or SPECCAST (note that gem5 has suffered some major changes since the patch was made. You should understand how gem5 m5ops work to use the gem5 option).

```
@@ -85,6 +85,9 @@ OPTIMIZATION_FLIBS=
 EXTRA_FPPFLAGS=
 FPPPORTABILITY=
 FPPFLAGS=
+# Uncomment the lines corresponding to gem5 or spec_cast as needed.
+#FPPFLAGS+= -DGEM5
+#FPPFLAGS+= -DSPECCAST
 BENCH_FPPFLAGS=

@@ -283,10 +286,21 @@ FINAL_CFLAGS   += $(OPTIMIZE) $(COPTIMIZE)  $(FDO_OPTIMIZE) $(FDO_COPTIMIZE)
 FINAL_CXXFLAGS += $(OPTIMIZE) $(CXXOPTIMIZE) $(FDO_OPTIMIZE) $(FDO_CXXOPTIMIZE) $(PORTABILITY) $(CXXPORTABILITY)
 RAW_FFLAGS     += $(OPTIMIZE) $(FOPTIMIZE)   $(FDO_OPTIMIZE) $(FDO_FOPTIMIZE)   $(PORTABILITY) $(FPORTABILITY)
 
-# Now add all of the "extra" flags on the end.
-FINAL_CFLAGS   += $(EXTRA_CFLAGS)
-FINAL_CXXFLAGS += $(EXTRA_CXXFLAGS)
-RAW_FFLAGS     += $(EXTRA_FFLAGS)
+# Now add all of the "extra" flags on the end. including all the required to run on gem5 or spec_cast
+# Uncomment the lines corresponding to gem5 or spec_cast as needed (D_GNU_SOURCE is needed for both).
+FINAL_CFLAGS   += $(EXTRA_CFLAGS) -D_GNU_SOURCE 
+FINAL_CXXFLAGS += $(EXTRA_CXXFLAGS) 
+RAW_FFLAGS     += $(EXTRA_FFLAGS) 
+
+#GEM5 flags
+#FINAL_CFLAGS   += -DGEM5 -DM5OP_ADDR=0xFFFF0000 -DM5OP_PIC
+#FINAL_CXXFLAGS += -DGEM5 -DM5OP_ADDR=0xFFFF0000 -DM5OP_PIC
+#RAW_FFLAGS     += -DGEM5 -DM5OP_ADDR=0xFFFF0000 -DM5OP_PIC
+
+#SPEC_cast flags 
+#FINAL_CFLAGS   += -DSPECCAST -fPIC 
+#FINAL_CXXFLAGS += -DSPECCAST 
+#RAW_FFLAGS     += -DSPECCAST 

```
